package main

func main() {
	// fmt.Println("hello world")
	//forTest()
	// switchTest()
	//arrayTest()
	// sliceTest()
	// mapTest()
	// variadicTest()
	// closureTest()
	// recursionTest()
	// stringTest()
	// pointerTest()
	// structTest()
	// methodTest()
	// interfaceTest()
	// enumTest()
	// embedTest()
	// genericTest()
	// iterTest()
	// errorTest()
	// goroutineTest()
	channelTest()
}
